// <auto-generated />
using System;
using Anduin.PhotoRanking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anduin.PhotoRanking.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251218105821_AddFileMetadata")]
    partial class AddFileMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Anduin.PhotoRanking.Models.Album", b =>
                {
                    b.Property<string>("AlbumId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("AlbumScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("HighestScore")
                        .HasColumnType("REAL");

                    b.Property<double>("KnownRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("LowestScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StandardDeviation")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AlbumId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Anduin.PhotoRanking.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("IndependentScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Knownness")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("OverallScore")
                        .HasColumnType("REAL");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Anduin.PhotoRanking.Models.RatingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("RatingLogs");
                });

            modelBuilder.Entity("Anduin.PhotoRanking.Models.Photo", b =>
                {
                    b.HasOne("Anduin.PhotoRanking.Models.Album", "Album")
                        .WithMany("Photos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Anduin.PhotoRanking.Models.RatingLog", b =>
                {
                    b.HasOne("Anduin.PhotoRanking.Models.Photo", "Photo")
                        .WithMany("RatingLogs")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Anduin.PhotoRanking.Models.Album", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Anduin.PhotoRanking.Models.Photo", b =>
                {
                    b.Navigation("RatingLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
